Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/legion/data/migrations/*.rb'
Metrics/MethodLength:
  Max: 30
Metrics/ClassLength:
  Max: 1500
Metrics/AbcSize:
  Max: 34
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'lib/legion/data/migrations/*'
Style/Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
Style/FrozenStringLiteralComment:
  Enabled: false
